#!/bin/sh

#initialise Vbuddy
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f toplevel.vcd

# run Verliator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace toplevel.sv --exe toplevel_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtoplevel.mk Vtoplevel

# run executable simulation 
obj_dir/Vtoplevel